### ISSUE TITLE
'context' raising python exceptions and not printing any output

### ISSUE THREAD

**Issue by lodi-g** [longld/peda#104]
For some reason PEDA fails to display the context for a program written in assembly.

Commands `context*` does not print anything but Python errors to the screen.

Running `context` raise this log:
```
Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_reference at 0x7ff832845ea0>, <__main__.PEDA object at 0x7ff832a3beb8>, (4196368,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_value at 0x7ff832845e18>, <__main__.PEDA object at 0x7ff832a3beb8>, (4196368,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.elfheader at 0x7ff83284a158>, <__main__.PEDA object at 0x7ff832a3beb8>, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.gdb/peda/peda.py", line 6055, in invoke
  File "~/.gdb/peda/peda.py", line 4434, in context
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 171, in wrapper
    f(*args, **kwargs)
  File "~/.gdb/peda/peda.py", line 4307, in context_register
  File "~/.gdb/peda/peda.py", line 4877, in xinfo
  File "~/.gdb/peda/peda.py", line 4865, in get_reg_text
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2163, in examine_mem_reference
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2107, in examine_mem_value
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2269, in elfheader
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

Running context_register:
```
Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_reference at 0x7ff832845ea0>, <__main__.PEDA object at 0x7ff832a3beb8>, (4196368,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_value at 0x7ff832845e18>, <__main__.PEDA object at 0x7ff832a3beb8>, (4196368,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.elfheader at 0x7ff83284a158>, <__main__.PEDA object at 0x7ff832a3beb8>, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.gdb/peda/peda.py", line 6055, in invoke
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 171, in wrapper
    f(*args, **kwargs)
  File "~/.gdb/peda/peda.py", line 4307, in context_register
  File "~/.gdb/peda/peda.py", line 4877, in xinfo
  File "~/.gdb/peda/peda.py", line 4865, in get_reg_text
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2163, in examine_mem_reference
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2107, in examine_mem_value
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2269, in elfheader
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

 `context_stack`:
```
Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_reference at 0x7ff832845ea0>, <__main__.PEDA object at 0x7ff832a3beb8>, (140737488346064,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.examine_mem_value at 0x7ff832845e18>, <__main__.PEDA object at 0x7ff832a3beb8>, (4196480,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function PEDA.elfheader at 0x7ff83284a158>, <__main__.PEDA object at 0x7ff832a3beb8>, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.gdb/peda/peda.py", line 6055, in invoke
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 171, in wrapper
    f(*args, **kwargs)
  File "~/.gdb/peda/peda.py", line 4397, in context_stack
  File "~/.gdb/peda/peda.py", line 4790, in telescope
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2177, in examine_mem_reference
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2107, in examine_mem_value
  File "/home/lodi_g/.gdb/peda/lib/utils.py", line 52, in __call__
    value = self.func(self.instance, *args, **kwargs)
  File "~/.gdb/peda/peda.py", line 2269, in elfheader
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

And `context_code` does not print anything.

Any insight on how to fix this? It looks like a TypeError is raised in the `except TypeError` block.

Thanks,

**Comment by longld** [comment]
Looks like it failed to parse ELF headers at: https://github.com/longld/peda/blob/master/peda.py#L2269

Output of command `maintenance info sections` might be useful to find out.

**Comment by lodi-g** [comment]
`maintenance info sections`:
```
Exec file:
    `/home/lodi_g/perso/asm/ash/ash', file type elf64-x86-64.
 [0]     0x00400238->0x00400254 at 0x00000238: .interp ALLOC LOAD READONLY DATA HAS_CONTENTS
 [1]     0x00400254->0x00400274 at 0x00000254: .note.ABI-tag ALLOC LOAD READONLY DATA HAS_CONTENTS
 [2]     0x00400274->0x00400298 at 0x00000274: .note.gnu.build-id ALLOC LOAD READONLY DATA HAS_CONTENTS
 [3]     0x00400298->0x004002e8 at 0x00000298: .gnu.hash ALLOC LOAD READONLY DATA HAS_CONTENTS
 [4]     0x004002e8->0x004004c8 at 0x000002e8: .dynsym ALLOC LOAD READONLY DATA HAS_CONTENTS
 [5]     0x004004c8->0x0040058b at 0x000004c8: .dynstr ALLOC LOAD READONLY DATA HAS_CONTENTS
 [6]     0x0040058c->0x004005b4 at 0x0000058c: .gnu.version ALLOC LOAD READONLY DATA HAS_CONTENTS
 [7]     0x004005b8->0x004005d8 at 0x000005b8: .gnu.version_r ALLOC LOAD READONLY DATA HAS_CONTENTS
 [8]     0x004005d8->0x00400608 at 0x000005d8: .rela.dyn ALLOC LOAD READONLY DATA HAS_CONTENTS
 [9]     0x00400608->0x00400728 at 0x00000608: .rela.plt ALLOC LOAD READONLY DATA HAS_CONTENTS
 [10]     0x00400728->0x0040073f at 0x00000728: .init ALLOC LOAD READONLY CODE HAS_CONTENTS
 [11]     0x00400740->0x00400810 at 0x00000740: .plt ALLOC LOAD READONLY CODE HAS_CONTENTS
 [12]     0x00400810->0x00400a62 at 0x00000810: .text ALLOC LOAD READONLY CODE HAS_CONTENTS
 [13]     0x00400a64->0x00400a6d at 0x00000a64: .fini ALLOC LOAD READONLY CODE HAS_CONTENTS
 [14]     0x00400a70->0x00400a74 at 0x00000a70: .rodata ALLOC LOAD READONLY DATA HAS_CONTENTS
 [15]     0x00400a74->0x00400b43 at 0x00000a74: .text: ALLOC LOAD READONLY DATA HAS_CONTENTS
 [16]     0x00400b43->0x00400b8d at 0x00000b43: .data: ALLOC LOAD READONLY DATA HAS_CONTENTS
 [17]     0x00400b90->0x00400bbc at 0x00000b90: .eh_frame_hdr ALLOC LOAD READONLY DATA HAS_CONTENTS
 [18]     0x00400bc0->0x00400c94 at 0x00000bc0: .eh_frame ALLOC LOAD READONLY DATA HAS_CONTENTS
 [19]     0x00600df8->0x00600e00 at 0x00000df8: .init_array ALLOC LOAD DATA HAS_CONTENTS
 [20]     0x00600e00->0x00600e08 at 0x00000e00: .fini_array ALLOC LOAD DATA HAS_CONTENTS
 [21]     0x00600e08->0x00600e10 at 0x00000e08: .jcr ALLOC LOAD DATA HAS_CONTENTS
 [22]     0x00600e10->0x00600ff0 at 0x00000e10: .dynamic ALLOC LOAD DATA HAS_CONTENTS
 [23]     0x00600ff0->0x00601000 at 0x00000ff0: .got ALLOC LOAD DATA HAS_CONTENTS
 [24]     0x00601000->0x00601078 at 0x00001000: .got.plt ALLOC LOAD DATA HAS_CONTENTS
 [25]     0x00601078->0x006010a7 at 0x00001078: .data ALLOC LOAD DATA HAS_CONTENTS
 [26]     0x006010a7->0x006010a8 at 0x000010a7: .bss ALLOC
 [27]     0x00000000->0x000002d0 at 0x000010a8: .stab READONLY HAS_CONTENTS
 [28]     0x00000000->0x0000001b at 0x00001378: .stabstr READONLY HAS_CONTENTS
 [29]     0x00000000->0x0000001a at 0x00001393: .comment READONLY HAS_CONTENTS
```

Also, I'm using `gef` right now but sometimes it throws errors: 
```[!] Command 'context' failed to execute properly, reason: Cannot access memory at address 0x0
0x0000000000000000 in ?? ()```

Thank you!

**Comment by longld** [comment]
Below lines break the parsing regex (it does not look like standard sections):
```
 [15]     0x00400a74->0x00400b43 at 0x00000a74: .text: ALLOC LOAD READONLY DATA HAS_CONTENTS
 [16]     0x00400b43->0x00400b8d at 0x00000b43: .data: ALLOC LOAD READONLY DATA HAS_CONTENTS
```
Pls test again with quick fix in https://github.com/longld/peda/commit/bbf58727b467ccdc8db6c5c6e2459d4ce19c1724

**Comment by lodi-g** [comment]
Just tried, looks like it's working. Thank you for the quick fix!
Also, if you got some free time, take a look at my PR :)

Thanks again!
