### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by sanjayc1** [longld/peda#166]
pulled latest from GIT repo and got following error with python 3.9.   

─── Assembly ──────────
Traceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 1370, in lines
  File "<string>", line 326, in fetch_breakpoints
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'info breakpoints'
─── Breakpoints ────────────
Traceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 2182, in lines
  File "<string>", line 326, in fetch_breakpoints
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'info breakpoints'
─── Expressions ──────
─── History ────────
─── Memory ────────
─── Registers ────────
raceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 1918, in lines
  File "<string>", line 2002, in fetch_register_list
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'maintenance print register-groups'
─── Source ────────
─── Stack ─────────
Traceback (most recent call last):
  File "/root/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function format_address at 0x7f8bb82fc4c0>, None, (4196052,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 1613, in lines
  File "<string>", line 1684, in get_pc_line
  File "/root/peda/lib/utils.py", line 50, in __call__
    value = self.func(*args, **kwargs)
TypeError: format_address() missing 1 required positional argument: 'type'
─── Threads ────────
Traceback (most recent call last):
  File "/root/peda/lib/utils.py", line 47, in __call__
    return self.cache[(self.func, self.instance, args) + tuple(kwargs.items())]
KeyError: (<function format_address at 0x7f8bb82fc4c0>, None, (4196052,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 542, in render
  File "<string>", line 2052, in lines
  File "<string>", line 1684, in get_pc_line
  File "/root/peda/lib/utils.py", line 50, in __call__
    value = self.func(*args, **kwargs)
TypeError: format_address() missing 1 required positional argument: 'type'
─── Variables ──────

**Comment by sanjayc1** [comment]
Issue was with echo "source ~/peda/peda.py" >> ~/.gdbinit.  Figured this was appending.  changed it to echo "source ~/peda/peda.py" > ~/.gdbinit  and that fixed the issue.  my ~/.gdbinit was old and python content in there was causing the issue.  I wish I saved it before overwriting it to find the root cause.
